export const SET_CATEGORIES_LIST_ACTION = "categories/SET_CATEGORIES_LIST";
export const SET_SELECTED_CATEGORIES_ID_ACTION =
  "categories/SET_SELECTED_CATEGORIES_ID_ACTION";
export const DELETE_CATEGORY_ITEM_ACTION =
  "categories/DELETE_CATEGORY_ITEM_ACTION";
export const UPDATE_CATEGORY_ITEM_ACTION =
  "categories/UPDATE_CATEGORY_ITEM_ACTION";
export const CREATE_CATEGORY_ITEM_ACTION =
  "categories/CREATE_CATEGORY_ITEM_ACTION";
